name: Build Game on Push
on:
  push:
    branches:
      - main
jobs:
  build-StandaloneWindows64:
    runs-on: ubuntu-latest
    steps:
    - uses: game-ci/unity-builder@v2
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      with:
        targetPlatform: StandaloneWindows64
        unityVersion: 2022.1.16f1
        projectPath: ./